import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { marked } from 'marked';
import { Person, Story } from './models.js';
import { sanitizeMarkdownHtml } from './security.js';

export function exportJSON(outputDir) {
  const data = { people: Person.getAll(), stories: Story.getAllWithPeople() };
  if (!existsSync(outputDir)) mkdirSync(outputDir, { recursive: true });
  const path = join(outputDir, 'cairn-export.json');
  writeFileSync(path, JSON.stringify(data, null, 2));
  return path;
}

export function exportHTML(outputDir) {
  if (!existsSync(outputDir)) mkdirSync(outputDir, { recursive: true });

  const people = Person.getAll();
  const stories = Story.getAllWithPeople();

  function buildIndex() {
    const personCards = people.map(p => `
      <div class="card">
        <a href="person-${p.id}.html">${escapeHtml(p.name)}</a>
        ${p.birth_date ? `<span class="date">${p.birth_date}${p.death_date ? ' — ' + p.death_date : ''}</span>` : ''}
        ${p.bio ? `<p class="preview">${escapeHtml(p.bio.substring(0, 200))}</p>` : ''}
      </div>`).join('');

    const storyCards = stories.map(s => `
      <div class="card">
        <a href="story-${s.id}.html">${escapeHtml(s.title)}</a>
        ${s.story_date ? `<span class="date">${s.story_date}</span>` : ''}
        <div class="tags">${(s.tags || []).map(t => `<span class="tag">${escapeHtml(t)}</span>`).join('')}</div>
      </div>`).join('');

    return page(`Cairn — ${getName()}`, `
      <h1>${getName()}</h1>
      <p class="subtitle">A living archive of memory</p>
      <hr>
      <h2>People (${people.length})</h2>
      <div class="grid">${personCards || '<p>No people recorded yet.</p>'}</div>
      <h2>Stories (${stories.length})</h2>
      <div class="grid">${storyCards || '<p>No stories recorded yet.</p>'}</div>
      <footer>
        <p>Generated by <a href="https://github.com/cairn-project/cairn">Cairn</a> on ${new Date().toLocaleDateString()}</p>
      </footer>
    `);
  }

  function buildPerson(p) {
    const rels = Person.getRelationships(p.id);
    const personStories = Story.getByPersonId(p.id);

    const relList = rels.map(r => `
      <li><a href="person-${r.related_person_id}.html">${escapeHtml(r.related_person_name)}</a> (${r.type})</li>`).join('');

    const storyList = personStories.map(s => `
      <li><a href="story-${s.id}.html">${escapeHtml(s.title)}</a>${s.story_date ? ' <span class="date">' + s.story_date + '</span>' : ''}</li>`).join('');

    return page(escapeHtml(p.name), `
      <nav><a href="index.html">← Home</a></nav>
      <h1>${escapeHtml(p.name)}</h1>
      ${p.birth_date ? `<p class="date">${p.birth_date}${p.death_date ? ' — ' + p.death_date : ''}</p>` : ''}
      ${p.bio ? `<div class="bio">${escapeHtml(p.bio)}</div>` : ''}
      ${rels.length ? `<h2>Relationships</h2><ul>${relList}</ul>` : ''}
      ${personStories.length ? `<h2>Stories</h2><ul>${storyList}</ul>` : ''}
      <footer><a href="index.html">← Back to Home</a></footer>
    `);
  }

  function buildStory(s) {
    const peopleLinks = (s.people || []).map(p =>
      `<a href="person-${p.id}.html">${escapeHtml(p.name)}</a>`).join(', ');

    return page(escapeHtml(s.title), `
      <nav><a href="index.html">← Home</a></nav>
      <h1>${escapeHtml(s.title)}</h1>
      ${s.story_date ? `<p class="date">${s.story_date}</p>` : ''}
      ${peopleLinks ? `<p class="people">With: ${peopleLinks}</p>` : ''}
      <div class="content">${sanitizeMarkdownHtml(marked.parse(s.content))}</div>
      ${(s.tags || []).length ? `<div class="tags">${s.tags.map(t => `<span class="tag">${escapeHtml(t)}</span>`).join('')}</div>` : ''}
      <footer><a href="index.html">← Back to Home</a></footer>
    `);
  }

  writeFileSync(join(outputDir, 'index.html'), buildIndex());
  for (const p of people) writeFileSync(join(outputDir, `person-${p.id}.html`), buildPerson(p));
  for (const s of stories) writeFileSync(join(outputDir, `story-${s.id}.html`), buildStory(s));

  writeFileSync(join(outputDir, 'style.css'), globalCSS);

  return outputDir;
}

function getName() {
  try { return Person.getAll()[0]?.name || 'My Archive'; } catch { return 'My Archive'; }
}

function escapeHtml(s) {
  if (!s) return '';
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

const globalCSS = `
body { font-family: Georgia, 'Times New Roman', serif; max-width: 800px; margin: 0 auto; padding: 2em 1em; color: #1a1a1a; background: #fafaf8; line-height: 1.7; }
a { color: #6b4c3b; text-decoration: none; }
a:hover { text-decoration: underline; }
h1, h2, h3 { font-weight: normal; color: #2d1f14; }
h1 { font-size: 2.2em; margin-bottom: 0.2em; }
.subtitle { color: #888; margin-top: 0; font-style: italic; }
.date { color: #888; font-size: 0.9em; }
.preview { color: #555; font-size: 0.95em; }
.grid { display: grid; gap: 1em; }
.card { background: white; padding: 1em 1.5em; border-radius: 8px; border: 1px solid #e8e4e0; }
.card a { font-size: 1.1em; display: block; margin-bottom: 0.2em; }
.tags { margin-top: 0.5em; }
.tag { display: inline-block; background: #ede8e3; color: #6b4c3b; padding: 0.1em 0.6em; border-radius: 3px; font-size: 0.8em; margin: 0.2em; }
.bio { white-space: pre-wrap; color: #444; }
.content { background: white; padding: 1.5em 2em; border-radius: 8px; border: 1px solid #e8e4e0; margin: 1em 0; }
.content p:first-child { margin-top: 0; }
nav { margin-bottom: 1em; }
footer { margin-top: 3em; padding-top: 1em; border-top: 1px solid #e8e4e0; color: #888; font-size: 0.9em; }
ul { padding-left: 1.5em; }
li { margin: 0.3em 0; }
.people { color: #666; }
hr { border: none; border-top: 1px solid #e8e4e0; margin: 2em 0; }
`;

function page(title, body) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>${body}</body>
</html>`;
}
